### ISSUE TITLE
implement 'range'

### ISSUE THREAD

**Issue by pervezfunctor** [technoidentity/devfractal-old#121]
We are currently not using any third party library like lodash or rxjs for higher order functions. Unfortunately range is not available in Javascript standard library. Let's implement it.
Interface for the function shoud be as following. Note that all of them are optional. Let's see if this is possible.

```typescript
range(start?: number, end?: number, step?: number)
```

**Comment by dandesravani** [comment]
closed in 4aaf2449393e1ad0874339af6889d4d201911eb8
