### ISSUE TITLE
Check whether all yup validations are supported in our validation library

### ISSUE THREAD

**Issue by swathivalasapalli** [technoidentity/devfractal-old#127]
please check if all the yup validations are supported in our validation library

**Comment by swathivalasapalli** [comment]
### List Of Functions missing in string

- string.ensure()
- string.matches()

### List Of Functions missing in number

- number.round()


### List of Functions missing in mixed

- mixed.clone()
- mixed.label()
- mixed.meta()
- mixed.describe()
- mixed.concat()
- mixed.validate()
- mixed.validateSync)
- mixed.validateAt()
- mixed.isValid()
- mixed.isValidSync()
- mixed.cast()
- mixed.isType()
- mixed.strict()
- mixed.strip()
- mixed.withMutation()
- mixed.default()
- mixed.nullable()
- mixed.notRequired()
- mixed.typeError()
- mixed.oneOf()
- mixed.notOneOf()
- mixed.when()
- mixed.test()
- mixed.transform()

**Comment by pervezfunctor** [comment]
you are dumb. What did I ask you to do and what did you do? Did I ask you to list all functions? Don't you even understand what validations are? And who asked you to create this issue?
