### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by pervezfunctor** [technoidentity/devfractal-old#175]
Fix all accessibility warnings. Now we have eslint checked accessibility, so learn about accessibility and fix all issues both in docs as well as lib.

**Comment by pervezfunctor** [comment]
Need to use eslint for lib too, to check for accessibility related issues. Need to look into axe and lighthouse.

**Comment by technoidentity** [comment]
eslint is integrated, a11y checked for most projects.
