### ISSUE TITLE
Implment Box, Content, Icon, Image and Title components from Bulma

### ISSUE THREAD

**Issue by technoidentity** [technoidentity/devfractal-old#18]
Documented at [Elements](https://bulma.io/documentation/elements/)

**Comment by swathivalasapalli** [comment]
There are no properties for Box element

**Comment by swathivalasapalli** [comment]
Box component closes in 1e27789001742a77fb5067abd81213f666353d02
Image component closes in 661422284c4def961f5e030bbf06f10ca5bd83e9
Icon component closes in 4f1b27cdb66778b8309a1fc3da846d5c0a103b7b
Title component closes in af44500436b719393c3deba2b006c7cc75cd8f60
