### ISSUE TITLE
Implement simple examples

### ISSUE THREAD

**Issue by technoidentity** [technoidentity/devfractal-old#6]
We will implement a lot of examples not only to understand the context for our project, but also as a way of explaining best practices for using `devfractal`.

Let's start simple. Implement a very simplistic `LoginForm` and `SignupForm` components using [Formik](https://jaredpalmer.com/formik). Perform validation using [Yup](https://github.com/jquense/yup). There probably are better options than Yup. But let's currently use Yup as Formik's documentation uses Yup.

We could also extract these components as semi reusable 'drop in' components later.t

**Comment by technoidentity** [comment]
Please implement these examples in formik/examples branch

**Comment by technoidentity** [comment]
I have made some changes to Login Form. Have a look at it and implement/reimplement Signup Form accordingly.

**Comment by venkateswarluk** [comment]
ok sir

**Comment by technoidentity** [comment]
I have done some quick refactorings. Please check if they work. Then, write the same forms using material-ui. Please push your code to mui branch.

**Comment by technoidentity** [comment]
Whenever you change code, like adding material-ui components, please check if it still works or not. I don't think your code works at all. I have added code in App.tsx for you to check if LoginForm works as expected.

Either write tests using react-testing-library or cypress. Or at least, check everything manually. Just committing some code which doesn't work doesn't serve any purpose.

Please also note that I cannot check every line of code to see if it works. It's your job to commit working code.

**Comment by technoidentity** [comment]
Use Field with mui components, currently you are explicitly passing properties like value, onChange.
