### ISSUE TITLE
Form components in Bulma

### ISSUE THREAD

**Issue by technoidentity** [technoidentity/devfractal-old#64]
List all form components in Bulma here. Let's first work on all form components, integrate them with formik and yup. Let's worry about everything else later.

**Comment by dandesravani** [comment]
1. Input
2. Textarea
3. Select
4. Checkbox
5. Radio
6. File
7. Dropdown
8. Button

**Comment by technoidentity** [comment]
Implement all of the above components and create an example form including all of those controls
