### ISSUE TITLE
Counter, Todo  and forms in reactstrap

### ISSUE THREAD

**Issue by technoidentity** [technoidentity/devfractal-old#69]
First Counter implement cheyi. Formik etc emi avasaram undadu. Chala easy ga ayipovali. Just reactstrap button component kavali. Properly grid use cheyi, text center cheyi chalu.
Next implement TodoApp using reactstrap components similar to http://todomvc.com/examples/backbone.  alane kanipinchadam avasaram ledu functionality unte chalu.
First, static version implement cheyi. Taruvata Formik to TextField integrate chesi raseyi. reactstrap lo Table component unte adi use cheyi. Use as many reactstrap components as possible. For example ButtonGroup.

Last ki SignupForm, LoginForm, ProductDetails forms implement cheyi. Ivi formik and reactstrap integrate chesi cheyalsi untundi. Formik padhatiga nerchukovali. Documentation chadovochu. Sravani already properly documentation chadvinattu undi. Documentation baane rasadu.

**Comment by technoidentity** [comment]
Separate branch create chesuko todo-reactstrap ani, reactstrap branch ninchi.

**Comment by pervezfunctor** [comment]
Let's worry about reactstrap in the next milestone.
